version: '3'

services:
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        ports:
            - 5000:5000
        environment:
            - CHOKIDAR_USEPOLLING=true
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

    gateway:
        build:
            dockerfile: Dockerfile.dev
            context: ./gateway
        ports:
            - 80:80
        depends_on:
            - "client"
            - "server"
